AWSTemplateFormatVersion: 2010-09-09

Description: "Create the WWW stack"

Parameters:
  CoreInfra:
    Description: The name of the core infrastucture stack
    Type: String
  Version:
    Default: 0.1.0
    Description: A version string to associate with this stack
    Type: String
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP, HTTPS and SSH to WWW instances.
      GroupName: !Sub "${AWS::StackName}-sg"
      VpcId:
        Fn::ImportValue:
          !Sub "${CoreInfra}-vpc"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: 'Environment'
          Value:
            Fn::ImportValue:
              !Sub "${CoreInfra}-environment"
        -
          Key: 'Name'
          Value: !Sub "${AWS::StackName}-sg"
        -
          Key: 'Stack version'
          Value:
            Ref: Version
  Instance:
    Type: AWS::EC2::Instance
    Properties:
        AvailabilityZone: !Select
          - 0
          - !Split
            - ','
            - Fn::ImportValue: !Sub "${CoreInfra}-az-list"
        IamInstanceProfile: 'puppet'
        ImageId: 'ami-996372fd'
        InstanceType: 't2.micro'
        KeyName: 'puppet'
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        SubnetId: !Select
          - 0
          - !Split
            - ','
            - Fn::ImportValue: !Sub "${CoreInfra}-public-subnets"
        Tags:
        -
          Key: 'Environment'
          Value:
            Fn::ImportValue:
              !Sub "${CoreInfra}-environment"
        -
          Key: 'Name'
          Value: !Sub "${AWS::StackName}"
        -
          Key: 'Stack version'
          Value:
            Ref: Version
        UserData: String
